/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimezonesIndexRouteImport } from './routes/timezones/index'
import { Route as LanguagesIndexRouteImport } from './routes/languages/index'
import { Route as CurrenciesIndexRouteImport } from './routes/currencies/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as ApiTimezonesRouteImport } from './routes/api/timezones'
import { Route as ApiLanguagesRouteImport } from './routes/api/languages'
import { Route as ApiCurrenciesRouteImport } from './routes/api/currencies'
import { Route as ApiCountriesRouteImport } from './routes/api/countries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimezonesIndexRoute = TimezonesIndexRouteImport.update({
  id: '/timezones/',
  path: '/timezones/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesIndexRoute = LanguagesIndexRouteImport.update({
  id: '/languages/',
  path: '/languages/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesIndexRoute = CurrenciesIndexRouteImport.update({
  id: '/currencies/',
  path: '/currencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimezonesRoute = ApiTimezonesRouteImport.update({
  id: '/api/timezones',
  path: '/api/timezones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLanguagesRoute = ApiLanguagesRouteImport.update({
  id: '/api/languages',
  path: '/api/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrenciesRoute = ApiCurrenciesRouteImport.update({
  id: '/api/currencies',
  path: '/api/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesRoute = ApiCountriesRouteImport.update({
  id: '/api/countries',
  path: '/api/countries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/currencies': typeof ApiCurrenciesRoute
  '/api/languages': typeof ApiLanguagesRoute
  '/api/timezones': typeof ApiTimezonesRoute
  '/api': typeof ApiIndexRoute
  '/compare': typeof CompareIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/languages': typeof LanguagesIndexRoute
  '/timezones': typeof TimezonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/currencies': typeof ApiCurrenciesRoute
  '/api/languages': typeof ApiLanguagesRoute
  '/api/timezones': typeof ApiTimezonesRoute
  '/api': typeof ApiIndexRoute
  '/compare': typeof CompareIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/languages': typeof LanguagesIndexRoute
  '/timezones': typeof TimezonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/currencies': typeof ApiCurrenciesRoute
  '/api/languages': typeof ApiLanguagesRoute
  '/api/timezones': typeof ApiTimezonesRoute
  '/api/': typeof ApiIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/languages/': typeof LanguagesIndexRoute
  '/timezones/': typeof TimezonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/countries'
    | '/api/currencies'
    | '/api/languages'
    | '/api/timezones'
    | '/api'
    | '/compare'
    | '/countries'
    | '/currencies'
    | '/languages'
    | '/timezones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/countries'
    | '/api/currencies'
    | '/api/languages'
    | '/api/timezones'
    | '/api'
    | '/compare'
    | '/countries'
    | '/currencies'
    | '/languages'
    | '/timezones'
  id:
    | '__root__'
    | '/'
    | '/api/countries'
    | '/api/currencies'
    | '/api/languages'
    | '/api/timezones'
    | '/api/'
    | '/compare/'
    | '/countries/'
    | '/currencies/'
    | '/languages/'
    | '/timezones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCountriesRoute: typeof ApiCountriesRoute
  ApiCurrenciesRoute: typeof ApiCurrenciesRoute
  ApiLanguagesRoute: typeof ApiLanguagesRoute
  ApiTimezonesRoute: typeof ApiTimezonesRoute
  ApiIndexRoute: typeof ApiIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  CurrenciesIndexRoute: typeof CurrenciesIndexRoute
  LanguagesIndexRoute: typeof LanguagesIndexRoute
  TimezonesIndexRoute: typeof TimezonesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timezones/': {
      id: '/timezones/'
      path: '/timezones'
      fullPath: '/timezones'
      preLoaderRoute: typeof TimezonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages/': {
      id: '/languages/'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/': {
      id: '/currencies/'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof CurrenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timezones': {
      id: '/api/timezones'
      path: '/api/timezones'
      fullPath: '/api/timezones'
      preLoaderRoute: typeof ApiTimezonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/languages': {
      id: '/api/languages'
      path: '/api/languages'
      fullPath: '/api/languages'
      preLoaderRoute: typeof ApiLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/currencies': {
      id: '/api/currencies'
      path: '/api/currencies'
      fullPath: '/api/currencies'
      preLoaderRoute: typeof ApiCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries': {
      id: '/api/countries'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCountriesRoute: ApiCountriesRoute,
  ApiCurrenciesRoute: ApiCurrenciesRoute,
  ApiLanguagesRoute: ApiLanguagesRoute,
  ApiTimezonesRoute: ApiTimezonesRoute,
  ApiIndexRoute: ApiIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  CurrenciesIndexRoute: CurrenciesIndexRoute,
  LanguagesIndexRoute: LanguagesIndexRoute,
  TimezonesIndexRoute: TimezonesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
