/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimezonesIndexRouteImport } from './routes/timezones/index'
import { Route as LanguagesIndexRouteImport } from './routes/languages/index'
import { Route as CurrenciesIndexRouteImport } from './routes/currencies/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimezonesIndexRoute = TimezonesIndexRouteImport.update({
  id: '/timezones/',
  path: '/timezones/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesIndexRoute = LanguagesIndexRouteImport.update({
  id: '/languages/',
  path: '/languages/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesIndexRoute = CurrenciesIndexRouteImport.update({
  id: '/currencies/',
  path: '/currencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries': typeof CountriesIndexRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/languages': typeof LanguagesIndexRoute
  '/timezones': typeof TimezonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countries': typeof CountriesIndexRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/languages': typeof LanguagesIndexRoute
  '/timezones': typeof TimezonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/languages/': typeof LanguagesIndexRoute
  '/timezones/': typeof TimezonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/countries' | '/currencies' | '/languages' | '/timezones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/countries' | '/currencies' | '/languages' | '/timezones'
  id:
    | '__root__'
    | '/'
    | '/countries/'
    | '/currencies/'
    | '/languages/'
    | '/timezones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  CurrenciesIndexRoute: typeof CurrenciesIndexRoute
  LanguagesIndexRoute: typeof LanguagesIndexRoute
  TimezonesIndexRoute: typeof TimezonesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timezones/': {
      id: '/timezones/'
      path: '/timezones'
      fullPath: '/timezones'
      preLoaderRoute: typeof TimezonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages/': {
      id: '/languages/'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/': {
      id: '/currencies/'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof CurrenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  CurrenciesIndexRoute: CurrenciesIndexRoute,
  LanguagesIndexRoute: LanguagesIndexRoute,
  TimezonesIndexRoute: TimezonesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
